version: '3.6'

services:
  sbt:
    image: hseeberger/scala-sbt:8u171_2.12.6_1.1.5
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/crud
      - DB_USER=crud
      - DB_PASSWORD=password
      - APP_PORT=8080
    links:
      - postgres
      - aerospike
    volumes:
      - ./:/app/
      - $HOME/.ivy2:/root/.ivy2
      - $HOME/.sbt/boot:/root/.sbt/boot
    entrypoint: sbt
    working_dir: /app
    ports:
      - 8080:8080


  postgres:
    image: postgres:10.4
    environment:
      - POSTGRES_USER=crud
      - POSTGRES_PASSWORD=password
    # expose port for easier testing and debugging
    ports:
      - 5432:5432

  aerospike:
    image: aerospike/aerospike-server:4.2.0.3
    # expose port for easier testing and debugging
    ports:
      - 3030:3000
    environment:
      - NAMESPACE=crud # unhardcode
